apiVersion: v1
kind: BuildConfig
metadata:
  name: repose-jenkins-build
spec:
  triggers:
    - type: ImageChange
      imageChange: {}
  source:
    git:
      uri: https://github.com/rackerlabs/repose
      ref: rsi-jenkins
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: repose-jenkins:latest
